BPR-5076 - business partner search in role assignment editor limited to user-all…
OpusCapita/user pull request #261
Opened 2020-09-29 11:34 UTC by ElaCzapiewska

business partner search in role assignment editor limited to user-allowed BPs

2020-09-29 12:06 UTC, jaconsta requested changes
Really nice work! I left some aesthetics changes.

2020-09-29 12:06 UTC, jaconsta commented on src/server/routes/index.js
> +    catch(err) {
is this catch required? The function is wrapped by a `catchError` middleware at L104

2020-09-29 12:06 UTC, jaconsta commented on src/client/api/User.js
> +
Please, remove the empty line

2020-09-29 12:06 UTC, jaconsta commented on src/server/acl.json
> +            {
Would be nice if only the correct resource groups are assigned to the new endpoint.

2020-09-29 14:44 UTC, ElaCzapiewska commented on src/server/api/BusinessPartner.js
> +                : '&id=' + this.userBusinessPartnerIds.join(',');
ok, changed

2020-09-29 14:44 UTC, ElaCzapiewska commented on src/server/api/BusinessPartner.js
> +}
ok, changed

2020-09-29 14:45 UTC, ElaCzapiewska commented on src/server/routes/index.js
> +const BusinessPartner = require('../api/BusinessPartner.js');
ok, changed, I move it upper, just under another recall of ../api/xx

2020-09-29 14:46 UTC, ElaCzapiewska commented on src/server/routes/index.js
> +    catch(err) {
right, corrected

2020-09-29 14:49 UTC, ElaCzapiewska commented on src/server/acl.json
> +            {
the new endpoint is now available only for assignable-role-mgmt, role-mgmt, x-tenant-user-mgmt resource groups. That means admin, customer-admin and supplier-admin can access it but user without one of these roles has no access to the endpoint

2020-09-30 07:24 UTC, jaconsta approved these changes
:rocket:  Super! please Squash and merge :)

2020-09-30 08:05 UTC, merged