feature/GENESIS-134-apply-BusinessPartnerAutocomplete-component
OpusCapita/user pull request #265
Opened 2020-11-10 17:49 UTC by ElaCzapiewska

get rid of BusinessPartnerSelect component introduced with GENESIS-21 and GENESIS-27,
use instead modified in the meantime BusinessPartnerAutocomplete component
offered by business-partner service

2020-11-11 14:48 UTC, jaconsta requested changes
It's really nice we are leaving the endpoint behind :). Please validate the ui's bouncer.getUserBusinessPartnerIds function.

2020-11-11 14:48 UTC, jaconsta commented on src/client/components/CreateRoleEditor/CreateRoleEditor.react.js
> +          this.userBusinessPartnerIds = context.bouncer.getUserTenants().map(tenant => tenant.replace(/^[s|c]_/, ''));
Would `getUserBusinessPartnerIds` work as we saw it's available in code?

2020-11-12 08:07 UTC, ElaCzapiewska commented on src/client/components/CreateRoleEditor/CreateRoleEditor.react.js
> +          this.userBusinessPartnerIds = context.bouncer.getUserTenants().map(tenant => tenant.replace(/^[s|c]_/, ''));
yes, there is ui's bouncer.getUserBusinessPartnerIds available and I would use it if it really returns businessPartnerIds, however it is an exact copy of getUserTenants function returning ids prefixed with c_ or s_ so still applying replace in map function is required. I can switch to getUserBusinessPartnerIds leaving map and replace, but we still need to remember to change the code when getUserBusinessPartnerIds start to return data without prefixes as map and replace will not interfere until we met bp whos pure id starts with c_ or s_. Please confirm what function should be used.

2020-11-12 10:36 UTC, jaconsta commented on src/client/components/CreateRoleEditor/CreateRoleEditor.react.js
> +          this.userBusinessPartnerIds = context.bouncer.getUserTenants().map(tenant => tenant.replace(/^[s|c]_/, ''));
I would prefer if we can stick with `getUserBusinessPartnerIds` since `getUserTenants` is in deprecated status and the replace won't be affected when the prefix doesn't exist anymore.

2020-11-12 11:19 UTC, ElaCzapiewska commented on src/client/components/CreateRoleEditor/CreateRoleEditor.react.js
> +          this.userBusinessPartnerIds = context.bouncer.getUserTenants().map(tenant => tenant.replace(/^[s|c]_/, ''));
ok changed

2020-11-12 17:33 UTC, jaconsta requested changes

2020-11-12 17:33 UTC, jaconsta commented on src/client/components/CreateRoleEditor/CreateRoleEditor.react.js
> +                    passParameter === 'ids'
Can we extract these props values to their own variable? This will help the readability of the components.

2020-11-12 18:21 UTC, ElaCzapiewska commented on src/client/components/CreateRoleEditor/CreateRoleEditor.react.js
> +                    passParameter === 'ids'
ok, extracted

2020-11-13 08:51 UTC, jaconsta approved these changes
:rocket:  Awesome!

2020-11-13 08:54 UTC, merged